export function downloadJSON(data: any, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  triggerDownload(blob, `${filename}.json`);
}

export function downloadTextAsPDF(title: string, sections: { heading: string; content: string }[], filename: string) {
  const html = `
    <html><head><title>${title}</title>
    <style>
      body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; padding: 20px; color: #1a1a1a; }
      h1 { font-size: 24px; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px; }
      h2 { font-size: 18px; margin-top: 28px; color: #333; }
      p, li { font-size: 14px; line-height: 1.7; }
      ul { padding-left: 20px; }
      .meta { font-size: 12px; color: #888; margin-bottom: 24px; }
      .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; background: #f0f0f0; margin-right: 6px; }
    </style></head><body>
    <h1>${title}</h1>
    <p class="meta">Exported on ${new Date().toLocaleDateString()} · Generated by AI Summarizer</p>
    ${sections.map(s => `<h2>${s.heading}</h2>${s.content}`).join("")}
    </body></html>`;
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 300);
  }
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportSummariesJSON(summaries: any[]) {
  downloadJSON(summaries.map(s => ({
    source: s.original_source,
    type: s.type,
    summary: s.summary_text,
    wordCount: s.word_count,
    createdAt: s.created_at,
  })), "summaries-export");
}

export function exportFlashcardsJSON(flashcards: { question: string; answer: string }[], source: string) {
  downloadJSON({ source, exportedAt: new Date().toISOString(), flashcards }, "flashcards-export");
}

export function exportHighlightsJSON(highlights: { timestamp: string; description: string; importance: string }[], source: string) {
  downloadJSON({ source, exportedAt: new Date().toISOString(), highlights }, "highlights-export");
}

export function exportFlashcardsPDF(flashcards: { question: string; answer: string }[], source: string) {
  downloadTextAsPDF(`Flashcards — ${source}`, flashcards.map((f, i) => ({
    heading: `Card ${i + 1}`,
    content: `<p><strong>Q:</strong> ${f.question}</p><p><strong>A:</strong> ${f.answer}</p>`,
  })), "flashcards");
}

export function exportHighlightsPDF(highlights: { timestamp: string; description: string; importance: string }[], source: string) {
  downloadTextAsPDF(`Highlights — ${source}`, highlights.map((h, i) => ({
    heading: `${h.timestamp}`,
    content: `<p><span class="badge">${h.importance}</span> ${h.description}</p>`,
  })), "highlights");
}

export function exportSummariesPDF(summaries: { original_source: string; summary_text: string; type: string; created_at: string }[]) {
  downloadTextAsPDF("My Summaries", summaries.map(s => ({
    heading: s.original_source || "Untitled",
    content: `<p class="meta">${s.type} · ${new Date(s.created_at).toLocaleDateString()}</p><p>${s.summary_text.substring(0, 2000)}</p>`,
  })), "summaries");
}
